version: "3.8"
services:
  frontend:
    container_name: monitor_frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    # environment:
    #   PORT: 3000
    #   HOST: "localhost"
    depends_on:
      - backend
  backend:
    container_name: monitor_backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 4400:4400
    environment:
      PORT: 4400
      FLASK_DEBUG: 1
